name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    name: build question-processor container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to Docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: martinmerlyn/question-processor:${{ github.ref_name }}, martinmerlyn/question-processor:latest